openapi: '3.0.0'
info:
  version: '1.0.0'
  title: 'Orders'
  description: Get or Save orders

paths:
  /orders/{orderId}:
    parameters:
      - name: orderId
        description: The unique order no
        in: path
        required: true
        schema:
          $ref: '#/components/schemas/OrderId'
    get:
      summary: Get Order Details
      responses:
        '200':
          description: Order Details corresponding to the provided `orderId`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderId'
        404:
          description: No order found for the provided `orderId`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    OrderId:
      description: The unique order no
      type: string
    OrderDetails:
      type: object
      required:
        - id
        - status
        - amount
      properties:
        id:
          $ref: '#/components/schemas/OrderId'
        status:
          type: string
        amount:
          type: number
    Error:
      type: object
      required:
        - message
      properties:
        message:
          description: A human readable error message
          type: string
  securitySchemes:
    ApiKey:
      type: apiKey
      in: header
      name: X-Api-Key
security:
  - ApiKey: []